version: '3'

services:
   grafana:
     build: rpi-grafana
     volumes:
       - grafana_data:/data
       - grafana_etc:/etc/grafana
     restart: always
     ports:
       - 3000

   telegraf:
      build: swestcott/rpi-telegraf
      volumes:
        - telegraf.conf:/etc/telegraf/telegraf.conf
      ports:
        - 9126:9126


volumes:
    grafana_data:
    grafana_etc:
    telegraf.conf:
